### PR TITLE
Handle erroneous issue file paths

### LINKED ISSUE #1537: Do not try to cache root file
The bot triggers an exception and publish a generic error message when it tries to run `load_file(".")`

Traceback from papertrail:

```
Feb 08 02:12:07 35.223.92.240 code-review/production/bot 2023-02-08 01:12:07 cli.py: Static analysis failure | extra={'revision': PHID-DIFF-ckzzedgdtiwpqfycaojq, 'error': IsADirectoryError(21, 'Is a directory'), 'exception': 'Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/code_review_bot-1.6.2-py3.10.egg/code_review_bot/cli.py", line 186, in main
    w.ingest_revision(revision, settings.autoland_group_id)
  File "/usr/local/lib/python3.10/site-packages/code_review_bot-1.6.2-py3.10.egg/code_review_bot/workflow.py", line 181, in ingest_revision
    self.backend_api.publish_issues(
  File "/usr/local/lib/python3.10/site-packages/code_review_bot-1.6.2-py3.10.egg/code_review_bot/backend.py", line 110, in publish_issues
    issue_hash = issue.build_hash(local_repository=mercurial_repository)
  File "/usr/local/lib/python3.10/site-packages/code_review_bot-1.6.2-py3.10.egg/code_review_bot/__init__.py", line 166, in build_hash
    file_content = self.revision.load_file(self.path)
  File "/usr/local/lib/python3.10/site-packages/code_review_bot-1.6.2-py3.10.egg/code_review_bot/revisions.py", line 296, in load_file
    with open(cache_path) as f:
IsADirectoryError: [Errno 21] Is a directory: \'/tmp/tmp1p59wg9rhgmo/.\''} 
```

You can see the full path with a trailing `.`.

Here is a task with that behaviour https://firefox-ci-tc.services.mozilla.com/tasks/AABjWvxfTWWvxPmMso2O7g

You can reproduce by using the following environment variable `      "AUTOLAND_TASK_GROUP_ID": "I-gz7SrkSCm6fSo2fGgcaQ"`

### PR DESCRIPTION
**Pull request by vrigal**
Closes #1537

### CODE REVIEW

**Comment by vrigal** [comment]
I could successfully ingest issues on the backend, file's content is ignored to build the issue :

```
2023-02-08 18:19:42.000700 [INFO    ] revisions.py: Downloading HGMO file
2023-02-08 18:19:44.000593 [WARNING ] revisions.py: Element with path '.' is not valid
2023-02-08 18:19:44.000593 [INFO    ] revisions.py: Downloading HGMO file
```

**Review by La0 — CHANGES_REQUESTED** [review]
Code is OK for me, could you simply add a unit test ?

It's easy to do as `load_file` is already tested in `test_hash`: just add a new case there which call `load_file` with a dummy issue's path set to `.`. It should then raise the expected ValueError

**Comment by vrigal** [comment]
I updated the code, which induce a change in the behavior of the bot : Issues missing a valid hash (wrong path, unreadable file…) are now skipped and will not be present in the backend. \
This is certainly an improvement though, as we can refer the same issue multiple times (from #1462) and it would have been confusing.

**Review by La0 — APPROVED** [review]
Now works on mentionned revision in issue.

The crashing issue now displays:
```
2023-02-09 14:49:09.000406 [WARNING ] revisions.py: Element with path '.' is not valid
2023-02-09 14:49:09.000414 [WARNING ] backend.py: Missing issue hash, cannot publish on backend
```

**Pull request merged**
