### PR TITLE
bot: Enforce coding & quotes PEP8 rules

### PR DESCRIPTION
**Pull request by La0**

### CODE REVIEW

**Comment by marco-c** [comment]
I would use black with pre-commit, so we have a common style between all projects. What do you think?

**Comment by La0** [comment]
I don't care as long as we are on the same page on every project.
This is just a port of release-services behaviour.

@marco-c Do you have black already setup as you want on bugbug or somewhere else ?

**Comment by marco-c** [comment]
> @marco-c Do you have black already setup as you want on bugbug or somewhere else ?

Yeah, on bugbug, relman-auto-nag and microannotate

**Comment by marco-c** [comment]
E.g. https://github.com/mozilla/microannotate/blob/master/.pre-commit-config.yaml.

**Pull request closed without merging**
