### PR TITLE
Add #taskgraph-reviewers on the Phabricator revision following the output of the TGDiff task

### LINKED ISSUE #1475: Add #taskgraph-reviewers to list of reviewers when the tgdiff task runs and identifies the revision as risky
This way taskgraph reviewers have visibility into these kind of changes.

### PR DESCRIPTION
**Pull request by EvaBardou**
Depends on https://github.com/mozilla/libmozdata/pull/214 being merged + a new release for **libmozdata**

Closes #1475

### CODE REVIEW

**Comment by EvaBardou** [comment]
I was able to publish a Phabricator comment on [this test patch](https://phabricator.services.mozilla.com/D171724#5650510) running the bot from my local instance, as you can see the reviewers group was correctly added:
> [reviewbot](https://phabricator.services.mozilla.com/p/reviewbot/) added a reviewer: [taskgraph-reviewers](https://phabricator.services.mozilla.com/tag/taskgraph-reviewers/).

**Review by marco-c — APPROVED** [review]
Would it be feasible to add a test for this?

**Comment by EvaBardou** [comment]
> Would it be feasible to add a test for this?

@marco-c I assume so, but I won't be able to write some before tomorrow's afternoon/Wednesday if you want to release this quickly as discussed on Matrix

**Comment by La0** [comment]
You also need to ignore the `summary.json` while listing the artifacts for files that changed.

Otherwise it will always report an issue about  this file being present (see https://phabricator.services.mozilla.com/D171872#5655051 & https://bugzilla.mozilla.org/show_bug.cgi?id=1819101#c4)

Basically just skip `summary.json` [here](https://github.com/mozilla/code-review/blob/master/bot/code_review_bot/tasks/tgdiff.py#L58)

**Comment by EvaBardou** [comment]
@marco-c I just added tests in https://github.com/mozilla/code-review/pull/1582/commits/18fe5fccfd665d17d46350dd0692deffe27eff33

@La0 I also added the logic to ignore the `summary.json` file while we load artifacts in https://github.com/mozilla/code-review/pull/1582/commits/15e7c71afb587765bc91b8d25b93a916a86e7247

**Review by marco-c — APPROVED** [review]

**Pull request merged**
