### PR TITLE
Store analyzers Taskcluster group on backend

### PR DESCRIPTION
**Pull request by La0**
Refs #187

### CODE REVIEW

**Comment by marco-c** [comment]
Why do we need it? Can't we use the index instead?

**Comment by La0** [comment]
It's for the frontend to display a link directly to the task group.
How could i access it from the TC Index ?

**Comment by marco-c** [comment]
> It's for the frontend to display a link directly to the task group.
How could i access it from the TC Index ?

From the diff ID you can access the TC indexed task, which is part of the group.
If this PR makes it easier to implement, that's OK.

**Comment by La0** [comment]
I'm closing for now, i'll try to use the index directly from the frontend. That will avoid storing deprecated group ids.

**Pull request closed without merging**
